import { NgbAccordionModule,
    NgbAlertModule, 
    NgbCarouselModule, 
    NgbCollapseModule, 
    NgbDatepickerModule, 
    NgbDropdownModule, 
    NgbModalModule, 
    NgbNavModule, 
    NgbPaginationModule, 
    NgbPopoverModule, 
    NgbProgressbarModule, 
    NgbRatingModule, 
    NgbTimepickerModule, 
    NgbToastModule, 
    NgbTooltipModule, 
    NgbTypeaheadModule } 
    from "@ng-bootstrap/ng-bootstrap";

export const BoostrapMaterial=[
   NgbAlertModule, 
   NgbAccordionModule, 
   NgbCarouselModule, 
   NgbCollapseModule, 
   NgbDatepickerModule, 
   NgbDropdownModule, 
   NgbModalModule, 
   NgbNavModule, 
   NgbPaginationModule, 
   NgbNavModule, 
   NgbPopoverModule, 
   NgbProgressbarModule, 
   NgbRatingModule, 
   NgbTimepickerModule, 
   NgbToastModule, 
   NgbTooltipModule, 
   NgbTypeaheadModule 
]